# Generated by Django 4.2.2 on 2023-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='full_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dish',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dish',
            name='lat_long',
            field=models.CharField(default='0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='dish',
            name='location',
            field=models.CharField(default='dummy', max_length=60),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default='name', max_length=150),
        ),
    ]
