# Generated by Django 4.2.2 on 2023-06-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_dish_full_details_dish_items_dish_lat_long_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='Restaurant',
        ),
    ]
